---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: subject
words: I,You,He,She,It,We,They

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought,slept,earned

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely,nice,awesome,awful,weird

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog,car,cup,cigarrete
